project:
  type: website
  output-dir: docs


website:
  title: "Applying to US Graduate School in Ecology, Evolution, and Related Fields"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



