---
title: " Applying to a PhD program in the US as an international student"
---

*From a blog post by [Rafael S. Marcondes](https://www.rafaelmarcondes.com/) made in 2017 for the Society for the Study of Evolution; the blog is no longer available, but Dr. Marcondes has given permission to use the content here.*


Rafael S. Marcondes, 2017
<https://www.rafaelmarcondes.com/>

I started doing research as an undergraduate student at the University of Sao Paulo in my native Brazil, and by the time I was starting my Masters at the same university I was very much set on a research career. But by then I had never seriously entertained the possibility of leaving Brazil for a PhD. I mean, the thought crossed my head, but I thought it wasn’t for me, and the process of finding a suitable advisor/lab, applying for a graduate program and moving overseas just seemed daunting to me. Nevertheless. Here I am now, starting my fifth year as a PhD student in the US and, looking back, the whole process prior to starting was surprisingly smooth! Retrospectively, I now see that the reason for that was that in my undergrad and Masters I was already immersed in a lab where international collaborations were commonplace, and that slowly changed my mindset. In particular, my decision to come to the US was heavily influenced by a postdoc who joined my Masters lab shortly after getting his PhD in the same lab I am now. He encouraged me and helped make the whole thing less terrifying. But I now realize how privileged I was to have had this relatively easy access to US academic culture. This is not the case for most other potential international students, and I have seen many talented young students in Brazil feeling deterred from applying to grad school in the US due to a lack of guidance and support. So I wanted to write this post to “pay forward” the help I had when applying to PhD programs in the U.S.

I acknowledge that this post will necessarily be biased by my own background and experiences. I come from Brazil, already held a Masters degree when I was applying, and I applied to a relatively small state university. Students from other national origins or targeting other types of universities may have different experiences. 

## First things first: how PhD students get paid

In Brazil, public education is completely free of cost, including at the graduate level, and students usually receive support during graduate school in the form of fellowships  that require them solely to make progress towards their degree. So it took me a while, back when I was applying and starting my PhD, to wrap my head around the system here in the US, where higher education is never free, and graduate students typically have to hold part-time jobs at their universities to pay for their education and make a living. I mention this early in this post because funding is one of the most important things you need to think very carefully about before deciding you really want to do a PhD in the US. 

The most common form of funding for graduate students is a teaching assistantship. That means that in addition to being a graduate student, you’ll also be employed by your university to teach classes for undergraduate students (with guidance and supervision from a professor). This can be a major cultural shock for international students unfamiliar with the US higher education system. The teaching load for teaching assistants (TAs) is very variable across types of institutions, but a common example would be teaching two weekly class sections each semester. With grading and preparation time, this can easily add up to 20 hrs/week, where you will be away from your research. In exchange for being a TA, you will receive a tuition exemption and a modest living stipend (salary). Exactly how modest is also variable, and a topic for a whole additional blog post in itself. Suffice it to say now that in some universities these days graduate students are barely avoiding scratching the poverty line. Part of the reason for that is that, in addition to tuition, universities charge various other required “fees” that often add up to exorbitant amounts and are automatically discounted from your paycheck. (It worth noting, however, that in many places students are starting to organize to push back against those fees—check out #fiercefees on Twitter and this [Science article](https://www.science.org/content/article/push-graduate-student-unions-signals-deep-structural-shift-academia) about grad student unions being formed in some universities).

Another form of funding, one that might represent a lighter workload, is a research assistantship. As an RA, you’re hired by a professor to assist in a research project, in exchange for the same stipend and tuition exemption as a TA. That research project may or may not be the same as your dissertation research, depending on arrangements with your advisor. RAs are less common than TAs because they depend of professors having external funds (usually NSF grants) to pay them. 

One last form of funding, and by far the best, is through external fellowships, where you receive your funding from an institution other than your university. Many national governments and some non-governmental organizations (for example, the Fulbright Program) offer such fellowships, and they are usually highly competitive. Most fellowships come with no requirements other than pursuing your degree, which means you be able to put 100% of your time towards that. Some of them also cover your non-tuition fees, making your financial situation considerably more comfortable. It is absolutely crucial that you discuss funding with your potential advisor before you make your mind about applying.

## Finding an advisor

Speaking of potential advisors: choosing and contacting a potential advisor is one of the most crucial steps in securing a PhD position in evolutionary biology. This is very different than in the biomedical sciences, where might apply to a department or university without necessarily having a specific professor in mind. In evolution, you generally choose your advisor rather than choosing your school, and you choose him or her based on similar research interests. Sometimes in developing countries we only hear about famous universities like Harvard, Cornell, Yale and so on. But if your research interests lie mainly in some obscure subfield like--for example--the use of ultraconserved elements to infer evolutionary history of Amazonian passerine birds, and the most active researchers in that subfield are not in any of those glam universities, but rather in a little-known state university in a small state, that’s probably a much better fit for you. That’s not to say that you should not consider the reputation, infrastructure, location etc. of a university--you most definitely should! But the first consideration is for sure the fit between you and your prospective advisor. 
When perusing departmental and school application websites, you may read about “rotations.” Rotations are a system where in your first year in a PhD program you rotate between various labs/advisors before choosing your definitive one. It’s used mostly in the biomedical sciences and, as far as I know, is rarely done in our field. In evolution, you’re expected to contact your prospective advisor and discuss your application before applying.

## Making connections

Okay, so now you’ve identified a researcher whose research interests match yours and with whom you’d like to work. How do you go about contacting and introducing yourself to them? This is probably the most difficult part of applying to a PhD as an international student, because professors are typically reluctant to accept students who they have not met in person, which can be impractical for us. Most departments have a so-called “recruitment weekend,” where top applicants are invited for a two-day campus visit, with all expenses paid, to get to know the school and the professor. Students based in other countries, though, may not be invited, due to financial constraints for the department. Even so, I very highly recommend trying to meet and discuss your plans in person with your prospective advisor. This might be easy, for example, if you’re already in a lab in your home country that collaborates with your US advisor and that he or she might visit. (Actually, selecting an advisor that you already know in that way in a very good idea in general.) If you have any kind of support or resources that allow to travel internationally, by all means do it and go visit your potential campus. 

However you talk with your advisor (in person, via Skype, or via email, in order of preference), those conversations should serve as much for the professor to evaluate your credentials, as well as for you to evaluate how well you would fit in with your professor/lab/departments. Different professors have different styles about, for example, whether or not they keep tabs on how many hours students spend in the lab, whether they are a more “hands-off” or “hands-on” mentor, and to what extent they support a healthy personal and social environment in their labs. [Karolina Heyduk](https://x.com/kheyduk/status/1171854576695304202) on Twitter has a [helpful document](https://docs.google.com/document/d/1svLyzkceDGPxhANCfdnLPIDASzAxoXLsrZl0PqmtUMQ/edit?tab=t.0) to guide students about things they should be asking their prospective advisors.

## Standardized tests

Cool, now you’ve selected and met or corresponded with a professor, and he or she has agreed to be your advisor, should you be accepted by the department to join their graduate program. The next--and annoying--step is taking the standardized tests TOEFL and GRE. The TOEFL is to demonstrate your proficiency in English. It is run by a private company called ETS and is offered fairly frequently in testing centers around the world. Unfortunately, it will set you back up to about $200 in registration fees. The GRE is a test required of all grad school applicants in the US, international and domestic. Its purpose is to assess verbal, analytical and critical thinking skills expected from someone with a Bachelors degree. It is also run by ETS and offered in testing centers in most countries. It will set you back an additional $200 or so.

Minimum TOEFL and GRE score requirements are quite variable and you should consult your university to know what they are. There has been a movement recently to de-emphasize the GRE in graduate school admissions, and some schools have even removed that requirement. Even in places that still require it, though, in my experience admission committees and prospective advisors seem to weigh the GRE score much less heavily than the student’s previous research experience and level of ambition.

## The application

Ugh, the process is long and grueling, but you’re almost there! All you need to do now is submit your actual application online through your University’s website. This is a relatively easy step. Universities normally receive applications with a December/January deadline for admission in the fall semester of the following year, or (less commonly) with a May/June deadline for admission in the spring semester. Usually your application will include a CV and a statement of interest. The latter is typically a short letter describing your background, qualifications and some basic ideas of what kind of research you think you might want to pursue during your PhD. Emphasis here is on “basic.” In the U.S., unlike some other countries, you are usually not expected to have a well-delineated research project before entering the program. That will happen around the end of your first year.
For your application, you’ll also have to send copies of transcripts and diplomas from your previous degrees. These copies need to be translated to English by a certified translator, which unfortunately can be quite expensive. Finally, the last thing you’ll need with your application are 2-3 letters of recommendation from senior researchers or professors that can speak highly of your achievements and potential. These can be Masters or undergraduate research advisors, or simply professors with whom you took classes and interacted a lot during your undergraduate degree. Make sure to ask them for your letter with ample time before the deadline, and to provide them with a few pointers to remind them what your strengths are.

## Finally getting there

Congratulations! You submitted your application and, a couple months later, you received word that you have been approved for admission for the PhD program in your favorite university! There’s one last step now: getting your student visa. The type of visa that most international students need is the F-1 visa; some students funded by some types of external fellowships might need apply for the J-1 visa instead. Once you have been accepted by your school, they will mail you a document called an I-20 form. You will need that, along with a passport, so you can apply for your F-1, following the instructions of your local US embassy or consulate. The US Department of State has some helpful information [here](https://travel.state.gov/content/travel/en/us-visas/study/student-visa.html) about applying for a student visa. 
With that, you will be all set to pack your stuff and ship up to the US to chase your dreams! There are a range of other issues relevant to arriving and living in the US as an international student, including cultural shock, bureaucracy, finances and taxes. I don’t have space to address them here, but I hope they will be the subject of another post in the not-too-distant future.